import { lazy } from 'react';

const oop = {
  slug: 'oop',
  yearSemester: 'y1s2',
  title: { en: 'Object-Oriented Programming', ro: 'Programare Orientată pe Obiecte' },
  shortTitle: { en: 'OOP', ro: 'POO' },
  description: {
    en: 'C++ fundamentals: classes, constructors, operators, inheritance, templates, STL',
    ro: 'Bazele C++: clase, constructori, operatori, moștenire, șabloane, STL',
  },
  icon: '🧱',
  courses: [
    { id: 'oop-course_1', title: { en: 'Course 1: Introduction', ro: 'Cursul 1: Introducere' }, shortTitle: { en: 'C1: Introduction', ro: 'C1: Introducere' }, sectionCount: 6,
      sections: [
        { id: 'oop-course_1-glossary', title: { en: '1. Glossary', ro: '1. Glosar' } },
        { id: 'oop-course_1-os-arch', title: { en: '2. OS Arch', ro: '2. Arhitectura SO' } },
        { id: 'oop-course_1-cpp-history', title: { en: '3. C++ History', ro: '3. Istoria C++' } },
        { id: 'oop-course_1-c-to-cpp', title: { en: '4. C to C++', ro: '4. De la C la C++' } },
        { id: 'oop-course_1-data-members', title: { en: '5. Data Members', ro: '5. Membri date' } },
        { id: 'oop-course_1-methods', title: { en: '6. Methods', ro: '6. Metode' } },
      ],
      component: lazy(() => import('./courses/Course01.jsx')) },
    { id: 'oop-course_2', title: { en: 'Course 2: C++ Language Specifiers', ro: 'Cursul 2: Specificatori ai limbajului C++' }, shortTitle: { en: 'C2: Specifiers', ro: 'C2: Specificatori' }, sectionCount: 6,
      sections: [
        { id: 'oop-course_2-pointers', title: { en: '1. Pointers & Refs', ro: '1. Pointeri & Ref' } },
        { id: 'oop-course_2-references', title: { en: '2. Ref Props', ro: '2. Prop. referințe' } },
        { id: 'oop-course_2-overloading', title: { en: '3. Overloading', ro: '3. Supraîncărcare' } },
        { id: 'oop-course_2-null', title: { en: '4. NULL/nullptr', ro: '4. NULL/nullptr' } },
        { id: 'oop-course_2-const', title: { en: '5. const', ro: '5. const' } },
        { id: 'oop-course_2-friend', title: { en: '6. friend', ro: '6. friend' } },
      ],
      component: lazy(() => import('./courses/Course02.jsx')) },
    { id: 'oop-course_3', title: { en: 'Course 3: Creating an Object', ro: 'Cursul 3: Crearea unui obiect' }, shortTitle: { en: 'C3: Objects', ro: 'C3: Obiecte' }, sectionCount: 7,
      sections: [
        { id: 'oop-course_3-init-lists', title: { en: '1. Init Lists', ro: '1. Liste inițial.' } },
        { id: 'oop-course_3-constructors', title: { en: '2. Constructors', ro: '2. Constructori' } },
        { id: 'oop-course_3-const-ref', title: { en: '3. Const & Ref', ro: '3. Const & Ref' } },
        { id: 'oop-course_3-delegating', title: { en: '4. Delegating', ro: '4. Constr. delegat' } },
        { id: 'oop-course_3-value-types', title: { en: '5. Value Types', ro: '5. Tipuri valori' } },
        { id: 'oop-course_3-copy-move', title: { en: '6. Copy & Move', ro: '6. Copiere & Mut.' } },
        { id: 'oop-course_3-constraints', title: { en: '7. Constraints', ro: '7. Constrângeri' } },
      ],
      component: lazy(() => import('./courses/Course03.jsx')) },
    { id: 'oop-course_4', title: { en: 'Course 4: Operators', ro: 'Cursul 4: Operatori' }, shortTitle: { en: 'C4: Operators', ro: 'C4: Operatori' }, sectionCount: 6,
      sections: [
        { id: 'oop-course_4-destructor', title: { en: '1. Destructor', ro: '1. Destructor' } },
        { id: 'oop-course_4-cpp-operators', title: { en: '2. C++ Operators', ro: '2. Operatori C++' } },
        { id: 'oop-course_4-class-operators', title: { en: '3. Class Ops', ro: '3. Op. clase' } },
        { id: 'oop-course_4-arithmetic', title: { en: '4. Arithmetic', ro: '4. Aritmetici' } },
        { id: 'oop-course_4-comparison', title: { en: '5. Comparison', ro: '5. Comparație' } },
        { id: 'oop-course_4-assignment', title: { en: '6. Assignment', ro: '6. Atribuire' } },
      ],
      component: lazy(() => import('./courses/Course04.jsx')) },
    { id: 'oop-course_5', title: { en: 'Course 5: Inheritance', ro: 'Cursul 5: Moștenire' }, shortTitle: { en: 'C5: Inheritance', ro: 'C5: Moștenire' }, sectionCount: 6,
      sections: [
        { id: 'oop-course_5-inheritance', title: { en: '1. Inheritance', ro: '1. Moștenire' } },
        { id: 'oop-course_5-virtual', title: { en: '2. Virtual Methods', ro: '2. Metode virt.' } },
        { id: 'oop-course_5-vtables', title: { en: '3. vtables', ro: '3. vtable' } },
        { id: 'oop-course_5-covariance', title: { en: '4. Covariance', ro: '4. Covarianță' } },
        { id: 'oop-course_5-abstract', title: { en: '5. Abstract', ro: '5. Clase abstracte' } },
        { id: 'oop-course_5-memory', title: { en: '6. Memory Align', ro: '6. Aliniere mem.' } },
      ],
      component: lazy(() => import('./courses/Course05.jsx')) },
    { id: 'oop-course_6', title: { en: 'Course 6: Templates', ro: 'Cursul 6: Șabloane' }, shortTitle: { en: 'C6: Templates', ro: 'C6: Șabloane' }, sectionCount: 6,
      sections: [
        { id: 'oop-course_6-casts', title: { en: '1. Casts', ro: '1. Cast-uri' } },
        { id: 'oop-course_6-macros', title: { en: '2. Macros', ro: '2. Macro-uri' } },
        { id: 'oop-course_6-literals', title: { en: '3. Literals', ro: '3. Literali' } },
        { id: 'oop-course_6-func-templates', title: { en: '4. Func Templates', ro: '4. Șabl. funcții' } },
        { id: 'oop-course_6-class-templates', title: { en: '5. Class Templates', ro: '5. Șabl. clase' } },
        { id: 'oop-course_6-specialization', title: { en: '6. Specialization', ro: '6. Specializare' } },
      ],
      component: lazy(() => import('./courses/Course06.jsx')) },
    { id: 'oop-course_7', title: { en: 'Course 7: STL (1)', ro: 'Cursul 7: STL (1)' }, shortTitle: { en: 'C7: STL', ro: 'C7: STL' }, sectionCount: 6,
      sections: [
        { id: 'oop-course_7-sequence', title: { en: '1. Seq Containers', ro: '1. Cont. secvenț.' } },
        { id: 'oop-course_7-adaptors', title: { en: '2. Adaptors', ro: '2. Adaptori' } },
        { id: 'oop-course_7-streams', title: { en: '3. I/O Streams', ro: '3. Fluxuri I/O' } },
        { id: 'oop-course_7-strings', title: { en: '4. Strings', ro: '4. Șiruri' } },
        { id: 'oop-course_7-init-lists', title: { en: '5. Init Lists', ro: '5. Liste inițial.' } },
        { id: 'oop-course_7-iterators', title: { en: '6. Iterators', ro: '6. Iteratori' } },
      ],
      component: lazy(() => import('./courses/Course07.jsx')) },
  ],
  seminars: [],
  labs: [
    { id: 'oop-lab_1', title: { en: 'Lab 01: Introduction', ro: 'Lab 01: Introducere' }, shortTitle: { en: 'L1: Intro', ro: 'L1: Intro' }, component: lazy(() => import('./labs/Lab01.jsx')) },
    { id: 'oop-lab_1e', title: { en: 'Lab 01 Extra', ro: 'Lab 01 Extra' }, shortTitle: { en: 'L1 Extra', ro: 'L1 Extra' }, component: lazy(() => import('./labs/Lab01Extra.jsx')) },
    { id: 'oop-lab_2', title: { en: 'Lab 02: Classes & Comparisons', ro: 'Lab 02: Clase & Comparații' }, shortTitle: { en: 'L2: Classes', ro: 'L2: Clase' }, component: lazy(() => import('./labs/Lab02.jsx')) },
    { id: 'oop-lab_2e', title: { en: 'Lab 02 Extra: Movie Classes', ro: 'Lab 02 Extra: Clase Film' }, shortTitle: { en: 'L2E: Movies', ro: 'L2E: Filme' }, component: lazy(() => import('./labs/Lab02Extra.jsx')) },
    { id: 'oop-lab_3', title: { en: 'Lab 03: Classes', ro: 'Lab 03: Clase' }, shortTitle: { en: 'L3: Classes', ro: 'L3: Clase' }, component: lazy(() => import('./labs/Lab03.jsx')) },
    { id: 'oop-lab_3e', title: { en: 'Lab 03 Extra', ro: 'Lab 03 Extra' }, shortTitle: { en: 'L3 Extra', ro: 'L3 Extra' }, component: lazy(() => import('./labs/Lab03Extra.jsx')) },
    { id: 'oop-lab_4', title: { en: 'Lab 04: Sort Class', ro: 'Lab 04: Clasa Sort' }, shortTitle: { en: 'L4: Sort', ro: 'L4: Sort' }, component: lazy(() => import('./labs/Lab04.jsx')) },
    { id: 'oop-lab_5', title: { en: 'Lab 05: Number Class', ro: 'Lab 05: Clasa Number' }, shortTitle: { en: 'L5: Number', ro: 'L5: Number' }, component: lazy(() => import('./labs/Lab05.jsx')) },
    { id: 'oop-lab_5e', title: { en: 'Lab 05 Extra: Complex Class', ro: 'Lab 05 Extra: Clasa Complex' }, shortTitle: { en: 'L5E: Complex', ro: 'L5E: Complex' }, component: lazy(() => import('./labs/Lab05Extra.jsx')) },
    { id: 'oop-lab_6', title: { en: 'Lab 06: Car Racing (Polymorphism)', ro: 'Lab 06: Curse auto (Polimorfism)' }, shortTitle: { en: 'L6: Racing', ro: 'L6: Curse' }, component: lazy(() => import('./labs/Lab06.jsx')) },
    { id: 'oop-lab_6e', title: { en: 'Lab 06 Extra: JSON Classes', ro: 'Lab 06 Extra: Clase JSON' }, shortTitle: { en: 'L6E: JSON', ro: 'L6E: JSON' }, component: lazy(() => import('./labs/Lab06Extra.jsx')) },
    { id: 'oop-lab_7', title: { en: 'Lab 07: Literals & Templates', ro: 'Lab 07: Literali & Șabloane' }, shortTitle: { en: 'L7: Templates', ro: 'L7: Șabloane' }, component: lazy(() => import('./labs/Lab07.jsx')) },
    { id: 'oop-lab_7e', title: { en: 'Lab 07 Extra: Vector Template', ro: 'Lab 07 Extra: Șablon Vector' }, shortTitle: { en: 'L7E: Vector', ro: 'L7E: Vector' }, component: lazy(() => import('./labs/Lab07Extra.jsx')) },
  ],
  tests: [],
  practice: lazy(() => import('./practice/Practice.jsx')),
};

export default oop;
