import { lazy } from 'react';

const oop = {
  slug: 'oop',
  yearSemester: 'y1s2',
  title: { en: 'Object-Oriented Programming', ro: 'Programare Orientată pe Obiecte' },
  shortTitle: { en: 'OOP', ro: 'POO' },
  description: {
    en: 'C++ fundamentals: classes, constructors, operators, inheritance, templates, STL',
    ro: 'Bazele C++: clase, constructori, operatori, moștenire, șabloane, STL',
  },
  icon: '🧱',
  courses: [
    { id: 'oop-c1', title: { en: 'Course 1: Introduction to C++', ro: 'Cursul 1: Introducere în C++' }, shortTitle: { en: 'C1: Introduction', ro: 'C1: Introducere' }, sectionCount: 12, metaId: 'oop-c1', src: 'oop/courses/course-01.json' },
    { id: 'oop-c2', title: { en: 'Course 2: C++ Language Specifiers', ro: 'Cursul 2: Specificatori ai limbajului C++' }, shortTitle: { en: 'C2: Specifiers', ro: 'C2: Specificatori' }, sectionCount: 7, metaId: 'oop-c2', src: 'oop/courses/course-02.json' },
    { id: 'oop-c3', title: { en: 'Course 3: Creating an Object', ro: 'Cursul 3: Crearea unui obiect' }, shortTitle: { en: 'C3: Objects', ro: 'C3: Obiecte' }, sectionCount: 9, metaId: 'oop-c3', src: 'oop/courses/course-03.json' },
    { id: 'oop-c4', title: { en: 'Course 4: Destructors & Operators', ro: 'Cursul 4: Destructori si operatori' }, shortTitle: { en: 'C4: Operators', ro: 'C4: Operatori' }, sectionCount: 11, metaId: 'oop-c4', src: 'oop/courses/course-04.json' },
    { id: 'oop-c5', title: { en: 'Course 5: Inheritance & Virtual Methods', ro: 'Cursul 5: Mostenire si metode virtuale' }, shortTitle: { en: 'C5: Inheritance', ro: 'C5: Mostenire' }, sectionCount: 9, metaId: 'oop-c5', src: 'oop/courses/course-05.json' },
    { id: 'oop-c6', title: { en: 'Course 6: Casts, Macros & Templates', ro: 'Cursul 6: Cast-uri, macro-uri si sabloane' }, shortTitle: { en: 'C6: Templates', ro: 'C6: Sabloane' }, sectionCount: 9, metaId: 'oop-c6', src: 'oop/courses/course-06.json' },
    { id: 'oop-course_7', title: { en: 'Course 7: STL (1)', ro: 'Cursul 7: STL (1)' }, shortTitle: { en: 'C7: STL', ro: 'C7: STL' }, sectionCount: 6,
      sections: [
        { id: 'oop-course_7-sequence', title: { en: '1. Seq Containers', ro: '1. Cont. secvenț.' } },
        { id: 'oop-course_7-adaptors', title: { en: '2. Adaptors', ro: '2. Adaptori' } },
        { id: 'oop-course_7-streams', title: { en: '3. I/O Streams', ro: '3. Fluxuri I/O' } },
        { id: 'oop-course_7-strings', title: { en: '4. Strings', ro: '4. Șiruri' } },
        { id: 'oop-course_7-init-lists', title: { en: '5. Init Lists', ro: '5. Liste inițial.' } },
        { id: 'oop-course_7-iterators', title: { en: '6. Iterators', ro: '6. Iteratori' } },
      ],
      component: lazy(() => import('./courses/Course07.jsx')) },
  ],
  seminars: [],
  labs: [
    { id: 'oop-lab_1', title: { en: 'Lab 01: Introduction', ro: 'Lab 01: Introducere' }, shortTitle: { en: 'L1: Intro', ro: 'L1: Intro' }, component: lazy(() => import('./labs/Lab01.jsx')) },
    { id: 'oop-lab_1e', title: { en: 'Lab 01 Extra', ro: 'Lab 01 Extra' }, shortTitle: { en: 'L1 Extra', ro: 'L1 Extra' }, component: lazy(() => import('./labs/Lab01Extra.jsx')) },
    { id: 'oop-lab_2', title: { en: 'Lab 02: Classes & Comparisons', ro: 'Lab 02: Clase & Comparații' }, shortTitle: { en: 'L2: Classes', ro: 'L2: Clase' }, component: lazy(() => import('./labs/Lab02.jsx')) },
    { id: 'oop-lab_2e', title: { en: 'Lab 02 Extra: Movie Classes', ro: 'Lab 02 Extra: Clase Film' }, shortTitle: { en: 'L2E: Movies', ro: 'L2E: Filme' }, component: lazy(() => import('./labs/Lab02Extra.jsx')) },
    { id: 'oop-lab_3', title: { en: 'Lab 03: Classes', ro: 'Lab 03: Clase' }, shortTitle: { en: 'L3: Classes', ro: 'L3: Clase' }, component: lazy(() => import('./labs/Lab03.jsx')) },
    { id: 'oop-lab_3e', title: { en: 'Lab 03 Extra', ro: 'Lab 03 Extra' }, shortTitle: { en: 'L3 Extra', ro: 'L3 Extra' }, component: lazy(() => import('./labs/Lab03Extra.jsx')) },
    { id: 'oop-lab_4', title: { en: 'Lab 04: Sort Class', ro: 'Lab 04: Clasa Sort' }, shortTitle: { en: 'L4: Sort', ro: 'L4: Sort' }, component: lazy(() => import('./labs/Lab04.jsx')) },
    { id: 'oop-lab_5', title: { en: 'Lab 05: Number Class', ro: 'Lab 05: Clasa Number' }, shortTitle: { en: 'L5: Number', ro: 'L5: Number' }, component: lazy(() => import('./labs/Lab05.jsx')) },
    { id: 'oop-lab_5e', title: { en: 'Lab 05 Extra: Complex Class', ro: 'Lab 05 Extra: Clasa Complex' }, shortTitle: { en: 'L5E: Complex', ro: 'L5E: Complex' }, component: lazy(() => import('./labs/Lab05Extra.jsx')) },
    { id: 'oop-lab_6', title: { en: 'Lab 06: Car Racing (Polymorphism)', ro: 'Lab 06: Curse auto (Polimorfism)' }, shortTitle: { en: 'L6: Racing', ro: 'L6: Curse' }, component: lazy(() => import('./labs/Lab06.jsx')) },
    { id: 'oop-lab_6e', title: { en: 'Lab 06 Extra: JSON Classes', ro: 'Lab 06 Extra: Clase JSON' }, shortTitle: { en: 'L6E: JSON', ro: 'L6E: JSON' }, component: lazy(() => import('./labs/Lab06Extra.jsx')) },
    { id: 'oop-lab_7', title: { en: 'Lab 07: Literals & Templates', ro: 'Lab 07: Literali & Șabloane' }, shortTitle: { en: 'L7: Templates', ro: 'L7: Șabloane' }, component: lazy(() => import('./labs/Lab07.jsx')) },
    { id: 'oop-lab_7e', title: { en: 'Lab 07 Extra: Vector Template', ro: 'Lab 07 Extra: Șablon Vector' }, shortTitle: { en: 'L7E: Vector', ro: 'L7E: Vector' }, component: lazy(() => import('./labs/Lab07Extra.jsx')) },
  ],
  tests: [
    { id: 'examen2023-2024-t1-p1', title: { en: '2023-2024 T1 P1 — CircularString', ro: '2023-2024 T1 P1 — CircularString' }, shortTitle: { en: 'T1 P1: CircularString', ro: 'T1 P1: CircularString' }, src: 'oop/tests/examen2023-2024-t1-p1.json' },
    { id: 'examen2023-2024-t1-p2', title: { en: '2023-2024 T1 P2 — PriorityQueue', ro: '2023-2024 T1 P2 — PriorityQueue' }, shortTitle: { en: 'T1 P2: PriorityQueue', ro: 'T1 P2: PriorityQueue' }, src: 'oop/tests/examen2023-2024-t1-p2.json' },
    { id: 'examen2023-2024-t1-p3', title: { en: '2023-2024 T1 P3 — CharSet', ro: '2023-2024 T1 P3 — CharSet' }, shortTitle: { en: 'T1 P3: CharSet', ro: 'T1 P3: CharSet' }, src: 'oop/tests/examen2023-2024-t1-p3.json' },
    { id: 'examen2023-2024-t2-p1-2024', title: { en: '2023-2024 T2 P1 — MyVector', ro: '2023-2024 T2 P1 — MyVector' }, shortTitle: { en: 'T2 P1: MyVector', ro: 'T2 P1: MyVector' }, src: 'oop/tests/examen2023-2024-t2-p1-2024.json' },
    { id: 'examen2023-2024-t2-p2-2024', title: { en: '2023-2024 T2 P2 — Students', ro: '2023-2024 T2 P2 — Students' }, shortTitle: { en: 'T2 P2: Students', ro: 'T2 P2: Students' }, src: 'oop/tests/examen2023-2024-t2-p2-2024.json' },
    { id: 'examen2023-2024-t2-p3-2024', title: { en: '2023-2024 T2 P3 — BankAccount', ro: '2023-2024 T2 P3 — BankAccount' }, shortTitle: { en: 'T2 P3: BankAccount', ro: 'T2 P3: BankAccount' }, src: 'oop/tests/examen2023-2024-t2-p3-2024.json' },
    { id: 'examen2020-2021-model-model-test-1-lab-oop-1', title: { en: '2020-2021 Model T1 P1 — DoubleLinkedList', ro: '2020-2021 Model T1 P1 — DoubleLinkedList' }, shortTitle: { en: 'Model T1 P1: DoubleLinkedList', ro: 'Model T1 P1: DoubleLinkedList' }, src: 'oop/tests/examen2020-2021-model-model-test-1-lab-oop-1.json' },
    { id: 'examen2020-2021-model-model-test-1-lab-oop-2', title: { en: '2020-2021 Model T1 P2 — Catalog', ro: '2020-2021 Model T1 P2 — Catalog' }, shortTitle: { en: 'Model T1 P2: Catalog', ro: 'Model T1 P2: Catalog' }, src: 'oop/tests/examen2020-2021-model-model-test-1-lab-oop-2.json' },
    { id: 'examen2020-2021-model-model-test-1-lab-oop-3', title: { en: '2020-2021 Model T1 P3 — Calculator', ro: '2020-2021 Model T1 P3 — Calculator' }, shortTitle: { en: 'Model T1 P3: Calculator', ro: 'Model T1 P3: Calculator' }, src: 'oop/tests/examen2020-2021-model-model-test-1-lab-oop-3.json' },
    { id: 'examen2020-2021-model-model-test-2-lab-oop-1', title: { en: '2020-2021 Model T2 P1 — Biblioteca', ro: '2020-2021 Model T2 P1 — Biblioteca' }, shortTitle: { en: 'Model T2 P1: Biblioteca', ro: 'Model T2 P1: Biblioteca' }, src: 'oop/tests/examen2020-2021-model-model-test-2-lab-oop-1.json' },
    { id: 'examen2020-2021-model-model-test-2-lab-oop-2', title: { en: '2020-2021 Model T2 P2 — Number', ro: '2020-2021 Model T2 P2 — Number' }, shortTitle: { en: 'Model T2 P2: Number', ro: 'Model T2 P2: Number' }, src: 'oop/tests/examen2020-2021-model-model-test-2-lab-oop-2.json' },
    { id: 'examen2020-2021-model-model-test-2-lab-oop-3', title: { en: '2020-2021 Model T2 P3 — Database', ro: '2020-2021 Model T2 P3 — Database' }, shortTitle: { en: 'Model T2 P3: Database', ro: 'Model T2 P3: Database' }, src: 'oop/tests/examen2020-2021-model-model-test-2-lab-oop-3.json' },
    { id: 'examen2020-2021-restanta', title: { en: '2020-2021 Restanta — Quiz Collection', ro: '2020-2021 Restanta — Quiz Collection' }, shortTitle: { en: 'Restanta: Quiz', ro: 'Restanta: Quiz' }, src: 'oop/tests/examen2020-2021-restanta.json' },
    { id: 'examen2023-2024-t2-alti-ani-prob-biblioteca', title: { en: 'T2 Alti Ani — Biblioteca', ro: 'T2 Alti Ani — Biblioteca' }, shortTitle: { en: 'Alti Ani: Biblioteca', ro: 'Alti Ani: Biblioteca' }, src: 'oop/tests/examen2023-2024-t2-alti-ani-prob-biblioteca.json' },
    { id: 'examen2023-2024-t2-alti-ani-prob-cumparaturi', title: { en: 'T2 Alti Ani — Cumparaturi', ro: 'T2 Alti Ani — Cumparaturi' }, shortTitle: { en: 'Alti Ani: Cumparaturi', ro: 'Alti Ani: Cumparaturi' }, src: 'oop/tests/examen2023-2024-t2-alti-ani-prob-cumparaturi.json' },
  ],
  practice: lazy(() => import('./practice/Practice.jsx')),
};

export default oop;
