export const PALETTES = {
  slate: {
    id: 'slate',
    name: 'Slate',
    swatch: '#94a3b8',
    light: {
      navBg: '#e2e8f0',
      navText: '#1e293b',
      navHover: '#cbd5e1',
      contentTypeBg: '#f1f5f9',
      breadcrumbBg: '#f8fafc',
      contentBg: '#ffffff',
      contentText: '#1a1a1a',
      sidebarBg: '#f8fafc',
      sidebarBorder: '#e2e8f0',
      mutedText: '#64748b',
      border: '#e2e8f0',
      cardBg: '#ffffff',
      hoverBg: '#f1f5f9',
    },
    dark: {
      navBg: '#12122a',
      navText: '#e2e4e8',
      navHover: '#1e1e3a',
      contentTypeBg: '#161630',
      breadcrumbBg: '#1a1a32',
      contentBg: '#1e1e38',
      contentText: '#e2e4e8',
      sidebarBg: '#1a1a32',
      sidebarBorder: '#2a2a4a',
      mutedText: '#6b6d80',
      border: '#2a2a4a',
      cardBg: '#1e1e38',
      hoverBg: '#2a2a4a',
    },
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    swatch: '#a8a29e',
    light: {
      navBg: '#e7e5e4',
      navText: '#1c1917',
      navHover: '#d6d3d1',
      contentTypeBg: '#f5f5f4',
      breadcrumbBg: '#faf8f5',
      contentBg: '#fafaf9',
      contentText: '#1c1917',
      sidebarBg: '#f5f5f4',
      sidebarBorder: '#e7e5e4',
      mutedText: '#78716c',
      border: '#e7e5e4',
      cardBg: '#fafaf9',
      hoverBg: '#f5f5f4',
    },
    dark: {
      navBg: '#1c1917',
      navText: '#e7e5e4',
      navHover: '#292524',
      contentTypeBg: '#231f1c',
      breadcrumbBg: '#211e1b',
      contentBg: '#292524',
      contentText: '#e7e5e4',
      sidebarBg: '#211e1b',
      sidebarBorder: '#44403c',
      mutedText: '#78716c',
      border: '#44403c',
      cardBg: '#292524',
      hoverBg: '#44403c',
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    swatch: '#7393b8',
    light: {
      navBg: '#dbe4f0',
      navText: '#1e293b',
      navHover: '#c5d4e8',
      contentTypeBg: '#edf2fa',
      breadcrumbBg: '#f0f4ff',
      contentBg: '#f8faff',
      contentText: '#1a1a1a',
      sidebarBg: '#edf2fa',
      sidebarBorder: '#dbe4f0',
      mutedText: '#64748b',
      border: '#dbe4f0',
      cardBg: '#f8faff',
      hoverBg: '#edf2fa',
    },
    dark: {
      navBg: '#0f172a',
      navText: '#e2e8f0',
      navHover: '#1e293b',
      contentTypeBg: '#141d32',
      breadcrumbBg: '#162038',
      contentBg: '#1a2540',
      contentText: '#e2e8f0',
      sidebarBg: '#162038',
      sidebarBorder: '#1e3050',
      mutedText: '#475569',
      border: '#1e3050',
      cardBg: '#1a2540',
      hoverBg: '#1e3050',
    },
  },
  zinc: {
    id: 'zinc',
    name: 'Zinc',
    swatch: '#71717a',
    light: {
      navBg: '#e4e4e7',
      navText: '#18181b',
      navHover: '#d4d4d8',
      contentTypeBg: '#f4f4f5',
      breadcrumbBg: '#fafafa',
      contentBg: '#ffffff',
      contentText: '#18181b',
      sidebarBg: '#f4f4f5',
      sidebarBorder: '#e4e4e7',
      mutedText: '#71717a',
      border: '#e4e4e7',
      cardBg: '#ffffff',
      hoverBg: '#f4f4f5',
    },
    dark: {
      navBg: '#18181b',
      navText: '#fafafa',
      navHover: '#27272a',
      contentTypeBg: '#1e1e22',
      breadcrumbBg: '#202024',
      contentBg: '#27272a',
      contentText: '#fafafa',
      sidebarBg: '#202024',
      sidebarBorder: '#3f3f46',
      mutedText: '#71717a',
      border: '#3f3f46',
      cardBg: '#27272a',
      hoverBg: '#3f3f46',
    },
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    swatch: '#5a8a6a',
    light: {
      navBg: '#d8e5dc',
      navText: '#1a2e20',
      navHover: '#c4d8ca',
      contentTypeBg: '#ecf2ed',
      breadcrumbBg: '#f5f9f5',
      contentBg: '#f8fbf8',
      contentText: '#1a1a1a',
      sidebarBg: '#ecf2ed',
      sidebarBorder: '#d8e5dc',
      mutedText: '#5a7a64',
      border: '#d8e5dc',
      cardBg: '#f8fbf8',
      hoverBg: '#ecf2ed',
    },
    dark: {
      navBg: '#121a16',
      navText: '#d8e5dc',
      navHover: '#1d2a22',
      contentTypeBg: '#17211c',
      breadcrumbBg: '#1a2520',
      contentBg: '#1d2a22',
      contentText: '#d8e5dc',
      sidebarBg: '#1a2520',
      sidebarBorder: '#2a3e30',
      mutedText: '#5a7a64',
      border: '#2a3e30',
      cardBg: '#1d2a22',
      hoverBg: '#2a3e30',
    },
  },
};

export const DEFAULT_PALETTE = 'slate';

export function applyPalette(paletteId, isDark) {
  const palette = PALETTES[paletteId] || PALETTES[DEFAULT_PALETTE];
  const colors = isDark ? palette.dark : palette.light;
  const root = document.documentElement;
  Object.entries(colors).forEach(([key, value]) => {
    const cssVar = '--theme-' + key.replace(/([A-Z])/g, '-$1').toLowerCase();
    root.style.setProperty(cssVar, value);
  });
}
