import { lazy } from 'react';

const probStat = {
  slug: 'prob-stat',
  yearSemester: 'y1s2',
  title: { en: 'Probabilities & Statistics', ro: 'Probabilități și Statistică' },
  shortTitle: { en: 'Prob & Stat', ro: 'Prob & Stat' },
  description: {
    en: 'Probability theory, distributions, statistical inference',
    ro: 'Teoria probabilităților, distribuții, inferență statistică',
  },
  icon: '📊',
  courses: [
    {
      id: 'ps-c1',
      src: 'prob-stat/courses/course-01.json',
      metaId: 'ps-c1',
      title: { en: 'Course 1: Probability Spaces and Random Events', ro: 'Cursul 1: Spații de probabilitate și evenimente aleatoare' },
      shortTitle: { en: 'C1: Probability Spaces', ro: 'C1: Spații de probabilitate' },
      sectionCount: 7,
    },
    {
      id: 'ps-c2',
      src: 'prob-stat/courses/course-02.json',
      metaId: 'ps-c2',
      title: { en: 'Course 2: Conditional Probability and Independence', ro: 'Cursul 2: Probabilitate condiționată și independență' },
      shortTitle: { en: 'C2: Conditional Prob.', ro: 'C2: Prob. condiționată' },
      sectionCount: 6,
    },
    {
      id: 'ps-c3',
      src: 'prob-stat/courses/course-03.json',
      metaId: 'ps-c3',
      title: { en: 'Course 3: Probabilistic Schemes', ro: 'Cursul 3: Scheme probabilistice' },
      shortTitle: { en: 'C3: Prob. Schemes', ro: 'C3: Scheme probabilistice' },
      sectionCount: 6,
    },
    {
      id: 'ps-c4',
      src: 'prob-stat/courses/course-04.json',
      metaId: 'ps-c4',
      title: { en: 'Course 4: Discrete Random Variables', ro: 'Cursul 4: Variabile aleatoare discrete' },
      shortTitle: { en: 'C4: Discrete R.V.', ro: 'C4: V.A. discrete' },
      sectionCount: 6,
    },
    {
      id: 'ps-c5',
      src: 'prob-stat/courses/course-05.json',
      metaId: 'ps-c5',
      title: { en: 'Course 5: Joint Distributions and Independent R.V.', ro: 'Cursul 5: Repartiții comune și variabile aleatoare independente' },
      shortTitle: { en: 'C5: Joint Distributions', ro: 'C5: Repartiții comune' },
      sectionCount: 5,
    },
    {
      id: 'ps-c6',
      src: 'prob-stat/courses/course-06.json',
      metaId: 'ps-c6',
      title: { en: 'Course 6: Inequalities and Continuous Distributions', ro: 'Cursul 6: Inegalități și Distribuții Continue' },
      shortTitle: { en: 'C6: Inequalities', ro: 'C6: Inegalități' },
      sectionCount: 7,
    },
    {
      id: 'ps-c7',
      src: 'prob-stat/courses/course-07.json',
      metaId: 'ps-c7',
      title: { en: 'Course 7: Central Limit Theorem and Simulation', ro: 'Cursul 7: Teorema Limită Centrală și Simulare' },
      shortTitle: { en: 'C7: CLT & Simulation', ro: 'C7: TLC & Simulare' },
      sectionCount: 5,
    },
    {
      id: 'ps-c8',
      src: 'prob-stat/courses/course-08.json',
      metaId: 'ps-c8',
      title: { en: 'Course 8: Monte Carlo Simulation Methods', ro: 'Cursul 8: Metode de Simulare Monte Carlo' },
      shortTitle: { en: 'C8: Monte Carlo', ro: 'C8: Monte Carlo' },
      sectionCount: 6,
    },
    {
      id: 'ps-c9',
      src: 'prob-stat/courses/course-09.json',
      metaId: 'ps-c9',
      title: { en: 'Course 9: Randomized Algorithms and the Probabilistic Method', ro: 'Cursul 9: Algoritmi Randomizați și Metoda Probabilistică' },
      shortTitle: { en: 'C9: Randomized Algorithms', ro: 'C9: Algoritmi Randomizați' },
      sectionCount: 6,
    },
    {
      id: 'ps-c10',
      src: 'prob-stat/courses/course-10.json',
      metaId: 'ps-c10',
      title: { en: 'Course 10: Descriptive Statistics', ro: 'Cursul 10: Statistică Descriptivă' },
      shortTitle: { en: 'C10: Descriptive Stats', ro: 'C10: Statistică Descriptivă' },
      sectionCount: 6,
    },
  ],
  labs: [
    {
      id: 'ps-lab_1',
      title: { en: 'Lab 1: R and RStudio Introduction', ro: 'Lab 1: Introducere în R și RStudio' },
      shortTitle: { en: 'L1: R Intro', ro: 'L1: R Intro' },
      sectionCount: 7,
      component: lazy(() => import('./labs/Lab01.jsx')),
    },
    {
      id: 'ps-lab_2',
      title: { en: 'Lab 2: Monte Carlo Simulation', ro: 'Lab 2: Simulare Monte Carlo' },
      shortTitle: { en: 'L2: Monte Carlo', ro: 'L2: Monte Carlo' },
      sectionCount: 4,
      component: lazy(() => import('./labs/Lab02.jsx')),
    },
    {
      id: 'ps-lab_3',
      title: { en: 'Lab 3: Random Algorithms', ro: 'Lab 3: Algoritmi Aleatori' },
      shortTitle: { en: 'L3: Rand Alg', ro: 'L3: Alg Aleatori' },
      sectionCount: 4,
      component: lazy(() => import('./labs/Lab03.jsx')),
    },
    {
      id: 'ps-lab_4',
      title: { en: 'Lab 4: Descriptive Statistics', ro: 'Lab 4: Statistică Descriptivă' },
      shortTitle: { en: 'L4: Desc Stat', ro: 'L4: Stat Descr' },
      sectionCount: 3,
      component: lazy(() => import('./labs/Lab04.jsx')),
    },
  ],
  tests: [
    {
      id: 'ps-tema-a',
      title: { en: 'Homework Theme A — Laplace, LLN, CLT', ro: 'Temă A — Laplace, LNM, TLC' },
      shortTitle: { en: 'Tema A', ro: 'Tema A' },
      sectionCount: 4,
      component: lazy(() => import('./tests/TemaA.jsx')),
    },
    {
      id: 'ps-tema-b',
      title: { en: 'Homework Theme B — Ellipsoid, Integrals, Social Network', ro: 'Temă B — Elipsoid, Integrale, Rețea Socială' },
      shortTitle: { en: 'Tema B', ro: 'Tema B' },
      sectionCount: 3,
      component: lazy(() => import('./tests/TemaB.jsx')),
    },
    {
      id: 'ps-tema-c',
      title: { en: 'Homework Theme C — Median Algorithm, Polynomial Identity', ro: 'Temă C — Algoritm Mediană, Identitate Polinoame' },
      shortTitle: { en: 'Tema C', ro: 'Tema C' },
      sectionCount: 2,
      component: lazy(() => import('./tests/TemaC.jsx')),
    },
    {
      id: 'ps-tema-d',
      title: { en: 'Homework Theme D — EU Unemployment Descriptive Stats', ro: 'Temă D — Statistică Descriptivă Șomaj UE' },
      shortTitle: { en: 'Tema D', ro: 'Tema D' },
      sectionCount: 1,
      component: lazy(() => import('./tests/TemaD.jsx')),
    },
  ],
  practice: lazy(() => import('./practice/Practice.jsx')),
};

export default probStat;
