import { lazy } from 'react';

const os = {
  slug: 'os',
  yearSemester: 'y1s2',
  title: { en: 'Operating Systems', ro: 'Sisteme de Operare' },
  shortTitle: { en: 'OS', ro: 'SO' },
  description: {
    en: 'Linux systems programming: commands, shell, file I/O, processes, IPC, signals, ncurses',
    ro: 'Programare de sistem Linux: comenzi, shell, I/O fișiere, procese, IPC, signals, ncurses',
  },
  icon: '\uD83D\uDDA5\uFE0F',
  courses: [
    { id: 'os-c1', src: 'os/courses/course-01.json', metaId: 'os-c1',
      title: { en: 'Course 1: Basic Commands & Filesystems', ro: 'Cursul 1: Comenzi de baz\u0103 \u0219i sisteme de fi\u0219iere' },
      shortTitle: { en: 'C1: Commands & FS', ro: 'C1: Comenzi & FS' },
      sectionCount: 19 },
    { id: 'os-c2', src: 'os/courses/course-02.json', metaId: 'os-c2',
      title: { en: 'Course 2: Shell Interpreters', ro: 'Cursul 2: Interpretoare de comenzi' },
      shortTitle: { en: 'C2: Shell', ro: 'C2: Shell' },
      sectionCount: 16 },
    { id: 'os-c3', src: 'os/courses/course-03.json', metaId: 'os-c3',
      title: { en: 'Course 3: Bash Scripting', ro: 'Cursul 3: Scripting Bash' },
      shortTitle: { en: 'C3: Bash', ro: 'C3: Bash' },
      sectionCount: 20 },
    { id: 'os-c4', src: 'os/courses/course-04.json', metaId: 'os-c4',
      title: { en: 'Course 4: POSIX File I/O', ro: 'Cursul 4: I/O fi\u0219iere POSIX' },
      shortTitle: { en: 'C4: File I/O', ro: 'C4: I/O Fi\u0219iere' },
      sectionCount: 19 },
    { id: 'os-c5', src: 'os/courses/course-05.json', metaId: 'os-c5',
      title: { en: 'Course 5: File Locks & Concurrent Access', ro: 'Cursul 5: Blocaje pe fi\u0219iere \u0219i acces concurent' },
      shortTitle: { en: 'C5: File Locks', ro: 'C5: Blocaje' },
      sectionCount: 11 },
    { id: 'os-c6', src: 'os/courses/course-06.json', metaId: 'os-c6',
      title: { en: 'Course 6: fork() & wait()', ro: 'Cursul 6: fork() \u0219i wait()' },
      shortTitle: { en: 'C6: fork/wait', ro: 'C6: fork/wait' },
      sectionCount: 11 },
    { id: 'os-c7', src: 'os/courses/course-07.json', metaId: 'os-c7',
      title: { en: 'Course 7: exec()', ro: 'Cursul 7: exec()' },
      shortTitle: { en: 'C7: exec', ro: 'C7: exec' },
      sectionCount: 13 },
    { id: 'os-c8', src: 'os/courses/course-08.json', metaId: 'os-c8',
      title: { en: 'Course 8: mmap & Shared Memory', ro: 'Cursul 8: mmap \u0219i memorie partajat\u0103' },
      shortTitle: { en: 'C8: mmap/IPC', ro: 'C8: mmap/IPC' },
      sectionCount: 13 },
    { id: 'os-c9', src: 'os/courses/course-09.json', metaId: 'os-c9',
      title: { en: 'Course 9: Pipes & FIFOs', ro: 'Cursul 9: Pipes \u0219i FIFO-uri' },
      shortTitle: { en: 'C9: Pipes', ro: 'C9: Pipes' },
      sectionCount: 15 },
    { id: 'os-c10', src: 'os/courses/course-10.json', metaId: 'os-c10',
      title: { en: 'Course 10: POSIX Signals', ro: 'Cursul 10: Semnale POSIX' },
      shortTitle: { en: 'C10: Signals', ro: 'C10: Signals' },
      sectionCount: 11 },
    { id: 'os-c11', src: 'os/courses/course-11.json', metaId: 'os-c11',
      title: { en: 'Course 11: NCURSES', ro: 'Cursul 11: NCURSES' },
      shortTitle: { en: 'C11: ncurses', ro: 'C11: ncurses' },
      sectionCount: 7 },
  ],
  seminars: [
    { id: 's1', title: { en: 'Week 1: Basic Linux Commands (Solved)', ro: 'Săptămâna 1: Comenzi de bază Linux (Rezolvate)' }, shortTitle: { en: 'W1: Commands', ro: 'S1: Comenzi' }, component: lazy(() => import('./seminars/Seminar01.jsx')) },
    { id: 's2', title: { en: 'Week 2: Chained Commands & Pipelines (Solved)', ro: 'Săptămâna 2: Comenzi înlănțuite și pipeline-uri (Rezolvate)' }, shortTitle: { en: 'W2: Pipelines', ro: 'S2: Pipeline-uri' }, component: lazy(() => import('./seminars/Seminar02.jsx')) },
    { id: 's3', title: { en: 'Week 3: Bash Scripting (Solved)', ro: 'Săptămâna 3: Scripting Bash (Rezolvate)' }, shortTitle: { en: 'W3: Bash Scripts', ro: 'S3: Scripturi Bash' }, component: lazy(() => import('./seminars/Seminar03.jsx')) },
    { id: 's4', title: { en: 'Week 4: File I/O & Locking in C (Solved)', ro: 'Săptămâna 4: I/O fișiere și blocaje în C (Rezolvate)' }, shortTitle: { en: 'W4: File I/O', ro: 'S4: I/O fișiere' }, component: lazy(() => import('./seminars/Seminar04.jsx')) },
    { id: 's5', title: { en: 'Week 5: fork/wait/exec (Solved)', ro: 'Săptămâna 5: fork/wait/exec (Rezolvate)' }, shortTitle: { en: 'W5: Processes', ro: 'S5: Procese' }, component: lazy(() => import('./seminars/Seminar05.jsx')) },
    { id: 's6', title: { en: 'Week 6: mmap & Shared Memory (Solved)', ro: 'Săptămâna 6: mmap și memorie partajată (Rezolvate)' }, shortTitle: { en: 'W6: mmap/shm', ro: 'S6: mmap/shm' }, component: lazy(() => import('./seminars/Seminar06.jsx')) },
    { id: 's7', title: { en: 'Week 7: Pipes, FIFOs & Signals (Solved)', ro: 'Săptămâna 7: Pipes, FIFO-uri și Signals (Rezolvate)' }, shortTitle: { en: 'W7: Pipes/Signals', ro: 'S7: Pipes/Signals' }, component: lazy(() => import('./seminars/Seminar07.jsx')) },
  ],
  labs: [
    { id: 'lab_1', title: { en: 'Week 1: Simple Commands (Exercises)', ro: 'Săptămâna 1: Comenzi simple (Exerciții)' }, shortTitle: { en: 'W1: Commands', ro: 'S1: Comenzi' }, sectionCount: 13, component: lazy(() => import('./labs/Lab01.jsx')) },
    { id: 'lab_2', title: { en: 'Week 2: Chained Commands & Pipelines (Exercises)', ro: 'Săptămâna 2: Comenzi înlănțuite și pipeline-uri (Exerciții)' }, shortTitle: { en: 'W2: Pipelines', ro: 'S2: Pipeline-uri' }, sectionCount: 13, component: lazy(() => import('./labs/Lab02.jsx')) },
    { id: 'lab_3', title: { en: 'Week 3: Bash Scripting (Exercises)', ro: 'Săptămâna 3: Scripting Bash (Exerciții)' }, shortTitle: { en: 'W3: Bash Scripts', ro: 'S3: Scripturi Bash' }, sectionCount: 23, component: lazy(() => import('./labs/Lab03.jsx')) },
    { id: 'lab_4', title: { en: 'Week 4: File I/O & Locking in C (Exercises)', ro: 'Săptămâna 4: I/O fișiere și blocaje în C (Exerciții)' }, shortTitle: { en: 'W4: File I/O', ro: 'S4: I/O fișiere' }, sectionCount: 12, component: lazy(() => import('./labs/Lab04.jsx')) },
    { id: 'lab_5', title: { en: 'Week 5: fork/wait/exec (Exercises)', ro: 'Săptămâna 5: fork/wait/exec (Exerciții)' }, shortTitle: { en: 'W5: Processes', ro: 'S5: Procese' }, sectionCount: 9, component: lazy(() => import('./labs/Lab05.jsx')) },
    { id: 'lab_6', title: { en: 'Week 6: mmap & Shared Memory (Exercises)', ro: 'Săptămâna 6: mmap și memorie partajată (Exerciții)' }, shortTitle: { en: 'W6: mmap/shm', ro: 'S6: mmap/shm' }, sectionCount: 9, component: lazy(() => import('./labs/Lab06.jsx')) },
    { id: 'lab_7', title: { en: 'Week 7: Pipes, FIFOs & Signals (Exercises)', ro: 'Săptămâna 7: Pipes, FIFO-uri și Signals (Exerciții)' }, shortTitle: { en: 'W7: Pipes/Signals', ro: 'S7: Pipes/Signals' }, sectionCount: 10, component: lazy(() => import('./labs/Lab07.jsx')) },
  ],
  tests: [
    { id: 'test-lab1-7', title: { en: 'Test: Labs 1–7', ro: 'Test: Laboratoarele 1–7' }, shortTitle: { en: 'Labs 1–7', ro: 'Lab 1–7' }, component: lazy(() => import('./tests/TestLab1_7.jsx')) },
    { id: 'os-test-sample', src: 'os/tests/test-sample.json',
      title: { en: 'Sample Test: Linux Basics', ro: 'Test exemplu: Bazele Linux' },
      shortTitle: { en: 'Sample', ro: 'Exemplu' } },
    { id: 'os-tp1-2324-v1', src: 'os/tests/tp1-2023-2024-v1.json',
      title: { en: 'TP1 2023-2024 Variant 1', ro: 'TP1 2023-2024 Varianta 1' },
      shortTitle: { en: 'TP1 23-24 V1', ro: 'TP1 23-24 V1' } },
  ],
  practice: lazy(() => import('./practice/Practice.jsx')),
};

export default os;
