import { lazy } from 'react';

const os = {
  slug: 'os',
  yearSemester: 'y1s2',
  title: { en: 'Operating Systems', ro: 'Sisteme de Operare' },
  shortTitle: { en: 'OS', ro: 'SO' },
  description: {
    en: 'Linux systems programming: commands, shell, file I/O, processes, IPC, signals, ncurses',
    ro: 'Programare de sistem Linux: comenzi, shell, I/O fișiere, procese, IPC, signals, ncurses',
  },
  icon: '\uD83D\uDDA5\uFE0F',
  courses: [
    { id: 'course_1', title: { en: 'Course 1: Basic Linux Commands & Filesystems', ro: 'Cursul 1: Comenzi de bază Linux și sisteme de fișiere' }, shortTitle: { en: 'C1: Commands & FS', ro: 'C1: Comenzi & FS' }, sectionCount: 9,
      sections: [
        { id: 'course_1-intro', title: { en: '1. Commands Intro', ro: '1. Intro Comenzi' } },
        { id: 'course_1-users', title: { en: '2. Users & Auth', ro: '2. Utilizatori' } },
        { id: 'course_1-files', title: { en: '3. Files & FS', ro: '3. Fișiere & FS' } },
        { id: 'course_1-perms', title: { en: '4. Permissions', ro: '4. Permisiuni' } },
        { id: 'course_1-cmds', title: { en: '5. File Commands', ro: '5. Comenzi Fișiere' } },
        { id: 'course_1-proc', title: { en: '6. Processes', ro: '6. Procese' } },
        { id: 'course_1-trouble', title: { en: '7. Troubleshoot', ro: '7. Depanare' } },
        { id: 'course_1-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_1-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course01.jsx')) },
    { id: 'course_2', title: { en: 'Course 2: Shell Interpreters I - General Overview', ro: 'Cursul 2: Interpretoare de comenzi I - Prezentare generală' }, shortTitle: { en: 'C2: Shell I', ro: 'C2: Shell I' }, sectionCount: 10,
      sections: [
        { id: 'course_2-simple', title: { en: '1. Simple Cmds', ro: '1. Comenzi Simple' } },
        { id: 'course_2-bg', title: { en: '2. Background', ro: '2. Background' } },
        { id: 'course_2-redirect', title: { en: '3. I/O Redirect', ro: '3. Redirecționări' } },
        { id: 'course_2-exit', title: { en: '4. Exit Status', ro: '4. Cod de Exit' } },
        { id: 'course_2-pipe', title: { en: '5. Pipelines', ro: '5. Pipeline-uri' } },
        { id: 'course_2-compound', title: { en: '6. Compound Cmds', ro: '6. Comenzi Compuse' } },
        { id: 'course_2-glob', title: { en: '7. Globbing', ro: '7. Metacaractere' } },
        { id: 'course_2-config', title: { en: '8. Shell Config', ro: '8. Config Shell' } },
        { id: 'course_2-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_2-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course02.jsx')) },
    { id: 'course_3', title: { en: 'Course 3: Bash Scripting', ro: 'Cursul 3: Scripting Bash' }, shortTitle: { en: 'C3: Bash Script', ro: 'C3: Script Bash' }, sectionCount: 9,
      sections: [
        { id: 'course_3-scripts', title: { en: '1. Scripts & Shebang', ro: '1. Scripturi' } },
        { id: 'course_3-vars', title: { en: '2. Variables', ro: '2. Variabile' } },
        { id: 'course_3-special', title: { en: '3. Special Vars', ro: '3. Var. Speciale' } },
        { id: 'course_3-arith', title: { en: '4. Arithmetic', ro: '4. Aritmetică' } },
        { id: 'course_3-test', title: { en: '5. Conditionals', ro: '5. Condiții' } },
        { id: 'course_3-control', title: { en: '6. Control Flow', ro: '6. Structuri Ctrl' } },
        { id: 'course_3-funcs', title: { en: '7. Functions', ro: '7. Funcții' } },
        { id: 'course_3-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_3-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course03.jsx')) },
    { id: 'course_4', title: { en: 'Course 4: File I/O Primitives (POSIX + C stdlib)', ro: 'Cursul 4: Primitivele I/O pentru fișiere (POSIX + C stdlib)' }, shortTitle: { en: 'C4: File I/O', ro: 'C4: I/O Fișiere' }, sectionCount: 7,
      sections: [
        { id: 'course_4-api', title: { en: '1. POSIX vs C Lib', ro: '1. POSIX vs C' } },
        { id: 'course_4-posix', title: { en: '2. POSIX Core', ro: '2. Primitive POSIX' } },
        { id: 'course_4-dir', title: { en: '3. Directory Ops', ro: '3. Op. Directoare' } },
        { id: 'course_4-stdio', title: { en: '4. C stdio I/O', ro: '4. I/O C stdio' } },
        { id: 'course_4-cache', title: { en: '5. FS Cache', ro: '5. Cache FS' } },
        { id: 'course_4-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_4-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course04.jsx')) },
    { id: 'course_5', title: { en: 'Course 5: File Locking & Concurrent Access', ro: 'Cursul 5: Blocaje pe fișiere și acces concurent' }, shortTitle: { en: 'C5: File Locks', ro: 'C5: Blocaje' }, sectionCount: 7,
      sections: [
        { id: 'course_5-concur', title: { en: '1. Concurrency', ro: '1. Acces Concurent' } },
        { id: 'course_5-locks', title: { en: '2. fcntl() Locks', ro: '2. Blocaje fcntl()' } },
        { id: 'course_5-advisory', title: { en: '3. Advisory Locks', ro: '3. Blocaje Advisory' } },
        { id: 'course_5-optim', title: { en: '4. Optimized Lock', ro: '4. Blocare Optim.' } },
        { id: 'course_5-time', title: { en: '5. Exec Time', ro: '5. Timp Execuție' } },
        { id: 'course_5-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_5-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course05.jsx')) },
    { id: 'course_6', title: { en: 'Course 6: Process Management I - fork() & wait()', ro: 'Cursul 6: Gestiunea proceselor I - fork() și wait()' }, shortTitle: { en: 'C6: fork/wait', ro: 'C6: fork/wait' }, sectionCount: 7,
      sections: [
        { id: 'course_6-def', title: { en: '1. Program vs Proc', ro: '1. Program vs Proc' } },
        { id: 'course_6-info', title: { en: '2. Info Primitives', ro: '2. Primitive Info' } },
        { id: 'course_6-fork', title: { en: '3. fork()', ro: '3. fork()' } },
        { id: 'course_6-wait', title: { en: '4. wait()', ro: '4. wait()' } },
        { id: 'course_6-sync', title: { en: '5. Sync Points', ro: '5. Pct. Sincroniz.' } },
        { id: 'course_6-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_6-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course06.jsx')) },
    { id: 'course_7', title: { en: 'Course 7: Process Management II - exec()', ro: 'Cursul 7: Gestiunea proceselor II - exec()' }, shortTitle: { en: 'C7: exec', ro: 'C7: exec' }, sectionCount: 7,
      sections: [
        { id: 'course_7-concept', title: { en: '1. exec() Concept', ro: '1. Conceptul exec()' } },
        { id: 'course_7-family', title: { en: '2. exec Functions', ro: '2. Funcții exec' } },
        { id: 'course_7-survives', title: { en: '3. Survives exec', ro: '3. Ce suprav. exec' } },
        { id: 'course_7-forkexec', title: { en: '4. fork+exec', ro: '4. fork+exec' } },
        { id: 'course_7-redirect', title: { en: '5. FD & Redirect', ro: '5. FD & Redirecț.' } },
        { id: 'course_7-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_7-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course07.jsx')) },
    { id: 'course_8', title: { en: 'Course 8: Memory-Mapped Files, Shared Memory & Semaphores', ro: 'Cursul 8: Fișiere mapate în memorie, memorie partajată și semafoare' }, shortTitle: { en: 'C8: mmap/IPC', ro: 'C8: mmap/IPC' }, sectionCount: 8,
      sections: [
        { id: 'course_8-concept', title: { en: '1. mmap Concept', ro: '1. Concept mmap' } },
        { id: 'course_8-mmap', title: { en: '2. mmap/munmap', ro: '2. mmap/munmap' } },
        { id: 'course_8-flags', title: { en: '3. PRIV vs SHARED', ro: '3. PRIV vs SHARED' } },
        { id: 'course_8-shm', title: { en: '4. POSIX Shared Mem', ro: '4. Mem. Partajată' } },
        { id: 'course_8-ipc', title: { en: '5. IPC Models', ro: '5. Modele IPC' } },
        { id: 'course_8-sem', title: { en: '6. Semaphores', ro: '6. Semafoare' } },
        { id: 'course_8-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_8-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course08.jsx')) },
    { id: 'course_9', title: { en: 'Course 9: IPC via Pipes (Anonymous & Named)', ro: 'Cursul 9: Comunicația inter-procese prin pipes (anonime și cu nume)' }, shortTitle: { en: 'C9: Pipes', ro: 'C9: Pipes' }, sectionCount: 8,
      sections: [
        { id: 'course_9-fund', title: { en: '1. Pipe Basics', ro: '1. Baze Pipe' } },
        { id: 'course_9-anon', title: { en: '2. Anon Pipes', ro: '2. Pipe-uri Anonime' } },
        { id: 'course_9-fifo', title: { en: '3. Named (FIFO)', ro: '3. Cu Nume (FIFO)' } },
        { id: 'course_9-block', title: { en: '4. Blocking', ro: '4. Comportament Bl.' } },
        { id: 'course_9-patterns', title: { en: '5. Comm Patterns', ro: '5. Șabloane Comunic' } },
        { id: 'course_9-apps', title: { en: '6. Applications', ro: '6. Aplicații' } },
        { id: 'course_9-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_9-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course09.jsx')) },
    { id: 'course_10', title: { en: 'Course 10: POSIX Signals', ro: 'Cursul 10: POSIX Signals' }, shortTitle: { en: 'C10: Signals', ro: 'C10: Signals' }, sectionCount: 8,
      sections: [
        { id: 'course_10-what', title: { en: '1. What is Signal', ro: '1. Ce e un Signal' } },
        { id: 'course_10-gen', title: { en: '2. Generating', ro: '2. Generare' } },
        { id: 'course_10-types', title: { en: '3. Signal Types', ro: '3. Tipuri Signals' } },
        { id: 'course_10-handle', title: { en: '4. signal() Handle', ro: '4. Tratare signal()' } },
        { id: 'course_10-block', title: { en: '5. Blocking', ro: '5. Blocare Signals' } },
        { id: 'course_10-wait', title: { en: '6. Waiting', ro: '6. Așteptare' } },
        { id: 'course_10-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_10-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course10.jsx')) },
    { id: 'course_11', title: { en: 'Course 11: NCURSES & Terminal Management', ro: 'Cursul 11: NCURSES și gestiunea terminalelor' }, shortTitle: { en: 'C11: ncurses', ro: 'C11: ncurses' }, sectionCount: 8,
      sections: [
        { id: 'course_11-concept', title: { en: '1. Phys vs Virtual', ro: '1. Fizic vs Virtual' } },
        { id: 'course_11-struct', title: { en: '2. Program Struct', ro: '2. Structura Prog.' } },
        { id: 'course_11-windows', title: { en: '3. Windows & Names', ro: '3. Ferestre & Nume' } },
        { id: 'course_11-io', title: { en: '4. Output & Input', ro: '4. Ieșire & Intrare' } },
        { id: 'course_11-color', title: { en: '5. Attrs & Colors', ro: '5. Atribute & Culori' } },
        { id: 'course_11-termios', title: { en: '6. termios', ro: '6. termios' } },
        { id: 'course_11-cheat', title: { en: 'Cheat Sheet', ro: 'Referință' } },
        { id: 'course_11-quiz', title: { en: 'Self-Test', ro: 'Autoevaluare' } },
      ],
      component: lazy(() => import('./courses/Course11.jsx')) },
    { id: 'os-c1-json', src: 'os/courses/course-01-sample.json' },
  ],
  seminars: [
    { id: 's1', title: { en: 'Week 1: Basic Linux Commands (Solved)', ro: 'Săptămâna 1: Comenzi de bază Linux (Rezolvate)' }, shortTitle: { en: 'W1: Commands', ro: 'S1: Comenzi' }, component: lazy(() => import('./seminars/Seminar01.jsx')) },
    { id: 's2', title: { en: 'Week 2: Chained Commands & Pipelines (Solved)', ro: 'Săptămâna 2: Comenzi înlănțuite și pipeline-uri (Rezolvate)' }, shortTitle: { en: 'W2: Pipelines', ro: 'S2: Pipeline-uri' }, component: lazy(() => import('./seminars/Seminar02.jsx')) },
    { id: 's3', title: { en: 'Week 3: Bash Scripting (Solved)', ro: 'Săptămâna 3: Scripting Bash (Rezolvate)' }, shortTitle: { en: 'W3: Bash Scripts', ro: 'S3: Scripturi Bash' }, component: lazy(() => import('./seminars/Seminar03.jsx')) },
    { id: 's4', title: { en: 'Week 4: File I/O & Locking in C (Solved)', ro: 'Săptămâna 4: I/O fișiere și blocaje în C (Rezolvate)' }, shortTitle: { en: 'W4: File I/O', ro: 'S4: I/O fișiere' }, component: lazy(() => import('./seminars/Seminar04.jsx')) },
    { id: 's5', title: { en: 'Week 5: fork/wait/exec (Solved)', ro: 'Săptămâna 5: fork/wait/exec (Rezolvate)' }, shortTitle: { en: 'W5: Processes', ro: 'S5: Procese' }, component: lazy(() => import('./seminars/Seminar05.jsx')) },
    { id: 's6', title: { en: 'Week 6: mmap & Shared Memory (Solved)', ro: 'Săptămâna 6: mmap și memorie partajată (Rezolvate)' }, shortTitle: { en: 'W6: mmap/shm', ro: 'S6: mmap/shm' }, component: lazy(() => import('./seminars/Seminar06.jsx')) },
    { id: 's7', title: { en: 'Week 7: Pipes, FIFOs & Signals (Solved)', ro: 'Săptămâna 7: Pipes, FIFO-uri și Signals (Rezolvate)' }, shortTitle: { en: 'W7: Pipes/Signals', ro: 'S7: Pipes/Signals' }, component: lazy(() => import('./seminars/Seminar07.jsx')) },
  ],
  labs: [
    { id: 'lab_1', title: { en: 'Week 1: Simple Commands (Exercises)', ro: 'Săptămâna 1: Comenzi simple (Exerciții)' }, shortTitle: { en: 'W1: Commands', ro: 'S1: Comenzi' }, sectionCount: 13, component: lazy(() => import('./labs/Lab01.jsx')) },
    { id: 'lab_2', title: { en: 'Week 2: Chained Commands & Pipelines (Exercises)', ro: 'Săptămâna 2: Comenzi înlănțuite și pipeline-uri (Exerciții)' }, shortTitle: { en: 'W2: Pipelines', ro: 'S2: Pipeline-uri' }, sectionCount: 13, component: lazy(() => import('./labs/Lab02.jsx')) },
    { id: 'lab_3', title: { en: 'Week 3: Bash Scripting (Exercises)', ro: 'Săptămâna 3: Scripting Bash (Exerciții)' }, shortTitle: { en: 'W3: Bash Scripts', ro: 'S3: Scripturi Bash' }, sectionCount: 23, component: lazy(() => import('./labs/Lab03.jsx')) },
    { id: 'lab_4', title: { en: 'Week 4: File I/O & Locking in C (Exercises)', ro: 'Săptămâna 4: I/O fișiere și blocaje în C (Exerciții)' }, shortTitle: { en: 'W4: File I/O', ro: 'S4: I/O fișiere' }, sectionCount: 12, component: lazy(() => import('./labs/Lab04.jsx')) },
    { id: 'lab_5', title: { en: 'Week 5: fork/wait/exec (Exercises)', ro: 'Săptămâna 5: fork/wait/exec (Exerciții)' }, shortTitle: { en: 'W5: Processes', ro: 'S5: Procese' }, sectionCount: 9, component: lazy(() => import('./labs/Lab05.jsx')) },
    { id: 'lab_6', title: { en: 'Week 6: mmap & Shared Memory (Exercises)', ro: 'Săptămâna 6: mmap și memorie partajată (Exerciții)' }, shortTitle: { en: 'W6: mmap/shm', ro: 'S6: mmap/shm' }, sectionCount: 9, component: lazy(() => import('./labs/Lab06.jsx')) },
    { id: 'lab_7', title: { en: 'Week 7: Pipes, FIFOs & Signals (Exercises)', ro: 'Săptămâna 7: Pipes, FIFO-uri și Signals (Exerciții)' }, shortTitle: { en: 'W7: Pipes/Signals', ro: 'S7: Pipes/Signals' }, sectionCount: 10, component: lazy(() => import('./labs/Lab07.jsx')) },
  ],
  tests: [
    { id: 'test-lab1-7', title: { en: 'Test: Labs 1–7', ro: 'Test: Laboratoarele 1–7' }, shortTitle: { en: 'Labs 1–7', ro: 'Lab 1–7' }, component: lazy(() => import('./tests/TestLab1_7.jsx')) },
  ],
  practice: lazy(() => import('./practice/Practice.jsx')),
};

export default os;
